POST http://localhost:3001/api/blogs/
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1hdHRtdXJveWEiLCJpZCI6IjYyNjI3NzRjMzg2MWU0NDU5Mzc4NmM1YiIsImlhdCI6MTY1MDYyMDI5MiwiZXhwIjoxNjUwNjIzODkyfQ.2ZG37RM7Ucm94i5N3rN1_nyZ-wQ4i_aaQW-qtKnSr-w

{
  "title": "test blog added with authentication",
  "author": "test author",
  "url": "mattmuroya.com",
  "likes": 1234,
  "userId": "6262774c3861e44593786c5b"
}