POST http://localhost:3001/api/blogs/
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1hdHRtdXJveWEiLCJpZCI6IjYyNWY4YWZjOWQxNDNiYjMyNzM3MTFhZSIsImlhdCI6MTY1MDU5NTQ3MX0.tv1cZQFQQo8QK0ub8n-Y46ptfuAFGNM1pQ85JtGNst

{
  "author": "matt m",
  "url": "mattmuroya.com",
  "likes": 1234,
  "userId": "625f8afc9d143bb3273711ae"
}