POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "root",
    "name": "Super User",
    "password": "secretpassword"
}

# {
#   "username": "mattmuroya",
#   "name": "Matt Muroya",
#   "password": "helloworld"
# }

# {
#   "username": "mttm",
#   "name": "MM"
# }

